# Generated by Django 4.0.3 on 2022-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='valor',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='valor',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
